import {
  faBoxes,
  faProjectDiagram,
  faUsers,
  faShoppingCart,
  faCalendarAlt,
  faHeadset,
  faTag,
  faList,
  faUser,
  faChartLine,
  faGavel,
  faPlus,
  faGlobe,
} from "@fortawesome/free-solid-svg-icons";

export const moduleDashboards = {
  projects: {
    key: "projects",
    label: "Projects",
    href: "/projectsdashboard",
    description: "Manage project planning, schedules and tracking.",
    icon: faProjectDiagram,
    sublinks: [
      { href: "/projects1", label: "Projects" },
      { href: "/projectdetails", label: "Project Details" },
      { href: "/openprojects", label: "Open Projects - Open PO's" },
      { href: "/tracking", label: "Tracking" },
      { href: "/lessons-learnt", label: "Lessons Learnt" },
      { href: "/longleadpackages", label: "Long Lead Material Packages" },
    ],
  },
  materials: {
    key: "materials",
    label: "Materials",
    href: "/materialsdashboard",
    description: "Track materials, documentation, and standardization.",
    icon: faBoxes,
    sublinks: [
      { href: "/materials1", label: "Materials" },
      { href: "/materialdocuments", label: "Material Docs" },
      { href: "/material-groups", label: "Material Groups" },
      { href: "/reqmatcode", label: "New Matcode" },
      { href: "/material-standardization", label: "Standardize Materials" },
    ],
  },
  purchaseorders: {
    key: "purchaseorders",
    label: "Purchase Orders",
    href: "/purchaseordersdashboard",
    description: "Manage purchase order lifecycle, alerts and feedback.",
    icon: faShoppingCart,
    sublinks: [
      { href: "/openpurchaseorders1", label: "Open PO" },
      { href: "/purchaseordersearch", label: "PO Complete Details" },
      { href: "/po-alert-report", label: "PO Alerts" },
      { href: "/purchases-report", label: "Comprehensive Purchases Report" },
    ],
  },
  vendors: {
    key: "vendors",
    label: "Vendors",
    href: "/vendorsdashboard",
    description: "Manage vendors, evaluations, and supplier performance.",
    icon: faUsers,
    sublinks: [
      { href: "/vendors1", label: "Vendors" },
      { href: "/vendor-dashboard", label: "Vendor Dashboard" },
      { href: "/nonsapvendors", label: "Non SAP Vendors" },
      { href: "/vendor-feedback", label: "Vendor Feedback" },
      { href: "/vendorevaluation/webformat", label: "Vendor Evaluation" },
    ],
  },
  projectdocumentss: {
    key: "projectdocumentss",
    label: "Project Documents",
    href: "/projectdocumentsdashboard",
    description: "Capture Project Document actions, follow-up items, and reviews.",
    icon: faCalendarAlt,
    sublinks: [
      { href: "/projectdocuments", label: "Project Documents" },
    ],
  },
  assets: {
    key: "assets",
    label: "Asset Management",
    href: "/assetdashboard",
    description: "Track fixed assets and equipment custody, and calibrations.",
    icon: faHeadset,
    sublinks: [
      { href: "/assets/dashboard", label: "Assets Dashboard" },
      { href: "/assetmanagement/masters", label: "Asset Masters" },
      { href: "/assets/mme", label: "MME Equipment" },
      { href: "/assets/fixedassets", label: "Fixed Assets" },
      { href: "/assets/ppe-dashboard", label: "PPE Dashboard" },
      { href: "/assets/reports", label: "Reports" },
    ],
  },
  globalmasters: {
    key: "globalmasters",
    label: "Global Masters",
    href: "/globalmastersdashboard",
    description: "Manage global master data including employees, departments, and configurations.",
    icon: faGlobe,
    sublinks: [
      { href: "/global-masters", label: "Global Masters" },
      { href: "/data-load", label: "Data Load", adminOnly: true },
    ],
  },
};

export const moduleCards = [
  moduleDashboards.projects,
  moduleDashboards.materials,
  moduleDashboards.purchaseorders,
  moduleDashboards.vendors,
  moduleDashboards.projectdocumentss,
  moduleDashboards.assets,
  moduleDashboards.globalmasters,
  {
    label: "Inventory Tags",
    href: "#",
    description: "Manage and track inventory tags.",
    icon: faTag,
    badge: "Coming Soon",
  },
  {
    label: "Material Classification",
    href: "#",
    description: "Organize and classify materials.",
    icon: faList,
    badge: "Coming Soon",
  },
  {
    label: "Vendor Registration",
    href: "#",
    description: "Onboard and register new vendors.",
    icon: faUser,
    badge: "Coming Soon",
  },
  {
    label: "Project Management",
    href: "#",
    description: "Advanced project planning and tracking.",
    icon: faChartLine,
    badge: "Coming Soon",
  },
  {
    label: "Scrap E-bid Marketplace",
    href: "#",
    description: "Marketplace for scrap and materials.",
    icon: faGavel,
    badge: "Coming Soon",
  },
  {
    label: "Future Module 1",
    href: "#",
    description: "Coming soon.",
    icon: faPlus,
  },
  {
    label: "Future Module 2",
    href: "#",
    description: "Coming soon.",
    icon: faPlus,
  },
  {
    label: "Future Module 3",
    href: "#",
    description: "Coming soon.",
    icon: faPlus,
  },
];
