import {
  faBoxes,
  faProjectDiagram,
  faUsers,
  faShoppingCart,
  faCalendarAlt,
  faHeadset,
  faTag,
  faList,
  faUser,
  faChartLine,
  faGavel,
  faPlus,
} from "@fortawesome/free-solid-svg-icons";

export const moduleDashboards = {
  projects: {
    key: "projects",
    label: "Projects",
    href: "/projectsdashboard",
    description: "Manage project planning, schedules and tracking.",
    icon: faProjectDiagram,
    sublinks: [
      { href: "/projects1", label: "Projects" },
      { href: "/projectdetails", label: "Project Details" },
      { href: "/openprojects", label: "Open Projects - Open PO's" },
      { href: "/tracking", label: "Tracking" },
      { href: "/lessons-learnt", label: "Lessons Learnt" },
      { href: "/longleadpackages", label: "Long Lead Material Packages" },
    ],
  },
  materials: {
    key: "materials",
    label: "Materials",
    href: "/materialsdashboard",
    description: "Track materials, documentation, and standardization.",
    icon: faBoxes,
    sublinks: [
      { href: "/materials1", label: "Materials" },
      { href: "/materialdocuments", label: "Material Docs" },
      { href: "/material-groups", label: "Material Groups" },
      { href: "/reqmatcode", label: "New Matcode" },
      { href: "/material-standardization", label: "Standardize Materials" },
    ],
  },
  purchaseorders: {
    key: "purchaseorders",
    label: "Purchase Orders",
    href: "/purchaseordersdashboard",
    description: "Manage purchase order lifecycle, alerts and feedback.",
    icon: faShoppingCart,
    sublinks: [
      { href: "/openpurchaseorders1", label: "Open PO" },
      { href: "/purchaseordersearch", label: "PO Complete Details" },
      { href: "/po-alert-report", label: "PO Alerts" },
      { href: "/po-feedback", label: "PO Feedback" },
      { href: "/po-comments", label: "PO Comments Summary" },
      { href: "/cash-po-materials-report", label: "Cash Purchases Dashboard" },
      { href: "/all-purchases-report", label: "All Purchases Report" },
      { href: "/domestic-purchases-report", label: "Within KSA/Domestic Purchases Details" },
      { href: "/import-purchases-report", label: "Import Purchases Details" },
      { href: "/services-purchases-report", label: "Services Purchases Details" },
      { href: "/channel-partner-purchases-report", label: "Channel partner Purchases Details" },
    ],
  },
  vendors: {
    key: "vendors",
    label: "Vendors",
    href: "/vendorsdashboard",
    description: "Manage vendors, evaluations, and supplier performance.",
    icon: faUsers,
    sublinks: [
      { href: "/vendors1", label: "Vendors" },
      { href: "/vendor-dashboard", label: "Vendor Dashboard" },
      { href: "/vendor-extract", label: "Vendor Extract (OpenAI)" },
      { href: "/vendorswithpo", label: "Vendor Details" },
      { href: "/vendorswithpo/not-evaluated-fixed", label: "Not Evaluated (Fixed Scores)" },
      { href: "/vendorevaluation/webformat", label: "Vendor Evaluation" },
      { href: "/vendors", label: "Non SAP Vendors" },
      { href: "/vendors/group-mapping", label: "Vendor Mapping" },
      { href: "/vendors/with-po-mapping", label: "Vendors with PO – Map Groups" },
      { href: "/vendor-feedback", label: "Vendor Feedback" },
      { href: "/vendordocupload", label: "Upload Documents" },
      { href: "/vendor-reports/no-purchaseorders", label: "Vendors w/o PO" },
      { href: "/vendor-reports/with-po-no-docs", label: "Vendors w/ PO - No Docs" },
      { href: "/vendor-reports/po-missing-docs", label: "Vendors w/ PO - Missing Docs" },
      { href: "/vendor-group-mapping", label: "Map groups to vendors" },
      { href: "/vendorevaluation/pdf/new", label: "Vendor Evaluation PDF" },
    ],
  },
  dailymeetings: {
    key: "dailymeetings",
    label: "Daily Meetings",
    href: "/dailymeetingdashboard",
    description: "Capture daily meeting actions, follow-up items, and reviews.",
    icon: faCalendarAlt,
    sublinks: [
      { href: "/dailymeeting", label: "Daily Meetings" },
    ],
  },
  assets: {
    key: "assets",
    label: "Asset Management",
    href: "/assetdashboard",
    description: "Track fixed assets and equipment custody, and calibrations.",
    icon: faHeadset,
    sublinks: [
      { href: "/assets/dashboard", label: "Assets Dashboard" },
      { href: "/assets/mme", label: "MME Equipment" },
      { href: "/assets/fixedassets", label: "Fixed Assets" },
      { href: "/assets/ppe-dashboard", label: "PPE Dashboard" },
      { href: "/assets/reports", label: "Reports" },
    ],
  },
};

export const moduleCards = [
  moduleDashboards.projects,
  moduleDashboards.materials,
  moduleDashboards.purchaseorders,
  moduleDashboards.vendors,
  moduleDashboards.dailymeetings,
  moduleDashboards.assets,
  {
    label: "Inventory Tags",
    href: "#",
    description: "Manage and track inventory tags.",
    icon: faTag,
    badge: "Coming Soon",
  },
  {
    label: "Material Classification",
    href: "#",
    description: "Organize and classify materials.",
    icon: faList,
    badge: "Coming Soon",
  },
  {
    label: "Vendor Registration",
    href: "#",
    description: "Onboard and register new vendors.",
    icon: faUser,
    badge: "Coming Soon",
  },
  {
    label: "Project Management",
    href: "#",
    description: "Advanced project planning and tracking.",
    icon: faChartLine,
    badge: "Coming Soon",
  },
  {
    label: "Scrap E-bid Marketplace",
    href: "#",
    description: "Marketplace for scrap and materials.",
    icon: faGavel,
    badge: "Coming Soon",
  },
  {
    label: "Future Module 1",
    href: "#",
    description: "Coming soon.",
    icon: faPlus,
  },
  {
    label: "Future Module 2",
    href: "#",
    description: "Coming soon.",
    icon: faPlus,
  },
  {
    label: "Future Module 3",
    href: "#",
    description: "Coming soon.",
    icon: faPlus,
  },
];
